### ISSUE TITLE
Is there a way to adjust the accuracy? Too much data

### ISSUE THREAD

**Issue by pdougla002** [xamarin/SignaturePad#23]
Is there a way to "scale" the pointF array? Our client's system has issues handling the amount data.

**Comment by mattleibow** [comment]
Thanks for suggesting this. I was considering this as well. Far too much data as a simple line can result in hundreds or even thousands of points

**Comment by mattleibow** [comment]
I have been doing some tests. On iOS (iPhone 6s), a straight shot diagonal makes about `20` points, and then is smoothed x40 to about 800 points. Way, way too much! On Android (Nexus 5), the initial points are more detailed at about 30 points, and this is smoothed x20 to about 600 points. Again, way more detail than needed.

On Windows, the ink manager does a bit of work for us and usually results in far fewer points.

**Comment by mattleibow** [comment]
With commit f50700753094e712a21c7295b0c4d65a96cc4b69, the number of points are slightly reduced by avoiding duplicate points.

**Comment by mattleibow** [comment]
I am closing this issue now as I have made a few tweaks to the smoothing granularity. Previously, the typical smoothing was about 20-40 points were created for each point drawn. This was a bit excessive since it was often the case that the points were pretty close together.

I basically reduced the number by 10x to about 2-4 points per point drawn. The lines appears smooth still, so I think it is OK. If this is still an issue, we can just re-open and increase the smoothing granularity.
