### ISSUE TITLE
ClearLabel can't be resized on iOS

### ISSUE THREAD

**Issue by juchom** [xamarin/SignaturePad#32]
If you set a text longer than clear, there is no way to resize the button.

The problem comes from this line I think:
https://github.com/xamarin/SignaturePad/blob/master/src/SignaturePad.iOS/SignaturePadView.cs#L637

the btnClear.Frame is not used after SizeToFit.

**Comment by mattleibow** [comment]
Thanks for this @juchom, this should be fixed in #31: https://github.com/mattleibow/SignaturePad/blob/xamarin-forms/src/SignaturePad.iOS/SignaturePadView.cs#L704

Let me know if this is what you are looking for. Basically, the clear button will be at the top right, with height as line-height and the width as the text width

**Comment by juchom** [comment]
Thanks for this quick fix. This looks good to me!

Any idea on when this will be pushed to nuget?
