### ISSUE TITLE
Points are inconsistent between each version

### ISSUE THREAD

**Issue by juchom** [xamarin/SignaturePad#33]
Trying to get the points for a signature on each Platform doesn't give the same results:

iOS:
https://github.com/xamarin/SignaturePad/blob/master/src/SignaturePad.iOS/SignaturePadView.cs#L61

//Create an array containing all of the points used to draw the signature.  Uses CGPoint.Empty 
//to indicate a new line. 
public CGPoint[] Points

Android:
https://github.com/xamarin/SignaturePad/blob/master/src/SignaturePad.Android/SignaturePadView.cs#L44

//Create an array containing all of the points used to draw the signature.  Uses null 
//to indicate a new line. 
public System.Drawing.PointF[] Points

Windows Mobile:
https://github.com/xamarin/SignaturePad/blob/master/src/SignaturePad.WP7/SignaturePad.xaml.cs#L35

//Create an array containing all of the points used to draw the signature.  Uses (-10000, -10000) 
//to indicate a new line. 
public Point [] Points

Would it be possible to have all 3 platforms returning Point or PointF and use the same standard for new line?

**Comment by mattleibow** [comment]
@juchom Thanks for pointing this out, it should be the native point system on each platform in #31. Also, Windows will now use (0,0) as a new line. I will be adding a new Lines property that will actually return the lines (arrays of points)

**Comment by mattleibow** [comment]
@juchom The reason we use System.Drawing.PointF on Android is because the native Point (Android.Graphics.Point) actually is a class that creates an underlying java object. So, if we were to use it, there would be more than double the memory usage, as well as extra overhead to manage it. iOS on the other hand is a struct GCPoint, and PointF is unavailable on Windows RT/UWP.
