### ISSUE TITLE
SignaturePad (Xamarin.Forms) not rendering on iOS(10) on a real device

### ISSUE THREAD

**Issue by voydz** [xamarin/SignaturePad#43]
Hi,

I am having trouble implementing the SignaturePad as a view in Xamarin.Forms. Using it like this:

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:signature="clr-namespace:SignaturePad.Forms;assembly=SignaturePad.Forms"
             x:Class="MyApp.Views.Util.SignaturePage"
             BackgroundColor="Aqua">

    <signature:SignaturePadView
        HorizontalOptions="FillAndExpand" 
        HeightRequest="150"
        CaptionText="Caption"
        CaptionTextColor="Blue"
        ClearText="Clear Text"
        ClearTextColor="Red"
        PromptText="Prompt text"
        PromptTextColor="Green"
        BackgroundColor="Gray"
        SignatureLineColor="White"
        StrokeWidth="2"
        StrokeColor="Maroon"/>

</ContentPage>
```

with `signature` beeing `xmlns:signature="clr-namespace:SignaturePad.Forms;assembly=SignaturePad.Forms"`. Do not get irritated by all the custom properties, I set them for debugging purposes.

Also I referenced the renderer in my ApplicationDelegate's FinishLaunching method as `var t = typeof(SignaturePad.Forms.iOS.SignaturePadRenderer);`.

The result is a gray screen, indicating that a view is rendered full-size over the aqua colored ContentPage. But there are no controls (no signature line, no clear button, I can't draw on it). I tried to test the library with the sample Xamarin.Forms project... But it is just not compiling.

For the records: In an iPhoneSimulator and generally on Android it is working just fine with the same view implementation.

Anybody got an hint on how to fix this issue?

thanks in advance,
Felix

EDIT: Some more information.

**Comment by rjcollingham** [comment]
I have this in my AppDelegate.cs and it works great on iOS 10 iPhone 7

`	
`[Register("AppDelegate")]
`public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
`{
`        public static Type dummyt = typeof(SignaturePad.Forms.iOS.SignaturePadRenderer); //<<-------
`

**Comment by voydz** [comment]
Hi @rjcollingham ,

thank you for your advice. I also tried this already (did not mention it in my initial post, though). Changing nothing in the result stated above. :(

**Comment by gtbuchanan** [comment]
It's due to linker settings in the build configuration. I actually had to create an instance of the renderer in AppDelegate to get it to work (pulled from [this comment][0], but I found only the renderer is necessary). Just referencing the type as mentioned above didn't work for me.

`var _ = new SignaturePad.Forms.iOS.SignaturePadRenderer();`

I have confirmed this works in release mode with "Link SDK Assemblies" set. Hopefully, we won't have to resort to stupid hacks like this in the future.

[0]: https://github.com/xamarin/SignaturePad/issues/39#issuecomment-256668142

**Comment by matthieugd** [comment]
@voydz did you find a solution ? I have the same problem and I also added the dummy code but still no   luck. It's a Xamarin Forms project 2.3.3.175 with SignaturePad 1.4.0.

**Comment by balaameex** [comment]
HI,

I also faced the same problem, after adding the  below code in App Delegate it solved the problem.
public static Type dummyt = typeof(SignaturePad.Forms.iOS.SignaturePadRenderer);

Thanks

**Comment by mattleibow** [comment]
Sometimes the linker links too much - and the linker is getting better.

One way that may be better is to use this type of "preserve":

```csharp
static bool falseflag = false;
static AppDelegate ()
{
    if (falseflag) {
        var ignore = new SignaturePad.Forms.iOS.SignaturePadRenderer ();
    }
}
```

This code will never get executed, but the linker will never know that.

But some good news! This is no longer necessary in v2.0 (as yet unreleased). This is avoided since we are using the same assembly via bait-and-switch. Also, we are directly indicating to the linker that the particular view is using a particular renderer. So there is now a "hard" link between the view and the platform render.
