### ISSUE TITLE
SignaturePadView not showing without Height-/WidthRequest set

### ISSUE THREAD

**Issue by olid4** [xamarin/SignaturePad#63]
It took me quite a while to figure out, that the SignaturePadView was not showing up, because I didn't set the HeightRequest and WidthRequest properties. This happened to me while programming on an Xamarin Forms PCL project and testing on iOS (simulator and device).

I think it should work with VerticalOptions and HorizontalOptions too:

```
            signPad = new SignaturePadView()
            {
                VerticalOptions = LayoutOptions.CenterAndExpand,
                HorizontalOptions = LayoutOptions.CenterAndExpand,
                BackgroundColor = Color.GhostWhite,
                StrokeColor = Color.Black,
                ClearTextColor = Color.Black,
                ClearText = "Neu",
                CaptionText = "Unterschrift",
                CaptionTextColor = Color.Black,
                StrokeWidth = 2,
                PromptText = "Hier unterschreiben",
                PromptTextColor = Color.Black,
                SignatureLineColor = Color.Black,

                // Remove the following two lines and SignaturePadView is not showing up
                HeightRequest = 200,
                WidthRequest = 600,
            };
```

**Comment by mattleibow** [comment]
This has been address in two ways:
 - the view now has a default size of 40x40
 - the view now only collapses as far as it can go, but still shows the various labels and button

The reason the collapsing actually happens is because the horizontal and vertical options are set to center. The correct way to make the signature view expand is with `FillAndExpand`.
