### ISSUE TITLE
SignaturePadView lost points and cannot load it

### ISSUE THREAD

**Issue by saramgsilva** [xamarin/SignaturePad#69]
Hello,

I have something like a wizard.

1. I have a page with few fields
2. I have a page with SignaturePadView
3. I have a page with few fields

When I fill 1, 2 and then go to 3, I can return to 2, and in this case my Points are missed.

If I set 

            _signaturePadView.Points = points;
            _signaturePadView.SignaturePadCanvas.Points = points;

it does not show the points.

Any suggestion?

**Comment by mattleibow** [comment]
Can you provide the device details? iOS, Android or UWP?

Also, are you able to confirm that `points` has data?

_note: you only need to do `signaturePadView.Points = points`, not both._

**Comment by mattleibow** [comment]
I tried to reproduce this on iOS, Android and UWP, but was unable. I wrote a test wizard app that you can try out on your device and see if that works: https://github.com/mattleibow/SignaturePadWizardDemo

If this works for you, we may have to look at your specific case, but I was not able to find your issue on any of my physical devices or emulators.

**Comment by saramgsilva** [comment]
Where is the sample that replicate my issue

**Comment by mattleibow** [comment]
I had a look at this code, and I think I see what is happening. Basically, your checks for what page to save/load the points are getting mixed.

In the `BackButton_OnClicked`, you are going backwards, but your check for the page is checking for Page2 and then setting the points. This won't happen as when you are going backwards, you are navigating **away** from Page2. To make this work, this check needs to go **after** the navigation.  **This appears to be the main problem.**

Secondly, in the same function, if you navigated from Page1 to Page2, and now are navigating back to Page1, you are not saving the points. This may be intentional, but just a note.

In the `NextButton_OnClicked` function, you are navigating forwards, and correctly saving the points. However, if you happened to navigate all the way back to Page1 from Page3, you will have lost the signature. Again, this may be intentional, but just in case, the reason for this is that you are not restoring the points at all in this function.

Here is your code, and some comments:

```csharp
private void BackButton_OnClicked(object sender, EventArgs e)
{
	// save the points before navigation
	if (index == 1)
	{
		_points = ((Page2)_contentPages[index]).Points;
	}

	// navigate
	if (index > 0)
	{
		_buttons[index].BackgroundColor = Color.MediumAquamarine;
		Pages.Children.Remove(_contentPages[index]);
		index--;
		_buttons[index].BackgroundColor = Color.GreenYellow;
		Pages.Children.Add(_contentPages[index]);
	}

	// restore the points after navigation
	if (index == 1 && _points != null)
	{
		((Page2)_contentPages[index]).SetPoints(_points);
	}
}

private void NextButton_OnClicked(object sender, EventArgs e)
{
	// save the points before navigation
	if (index == 1)
	{
		_points = ((Page2)_contentPages[index]).Points;
	}

	// navigate
	if (index + 1 < _contentPages.Count)
	{
		_buttons[index].BackgroundColor = Color.MediumAquamarine;
		Pages.Children.Remove(_contentPages[index]);
		index++;
		_buttons[index].BackgroundColor = Color.GreenYellow;
		Pages.Children.Add(_contentPages[index]);
	}

	// restore the points after navigation
	if (index == 1 && _points != null)
	{
		((Page2)_contentPages[index]).SetPoints(_points);
	}
}
```

I hope this helps.

**Comment by saramgsilva** [comment]
For the sample it works well, let's see if I can apply to my app...  it is similar behavior.

Thanks for the support.

**Comment by mattleibow** [comment]
No problem. Let me know how it goes.

**Comment by zacglenn** [comment]
Is this issue similar to this Stack Overflow issue? https://stackoverflow.com/questions/44167030/how-may-i-load-the-points-restore-the-points-to-display-a-signature/44167238?noredirect=1#comment75354251_44167238

**Comment by saramgsilva** [comment]
For me it is working, that solution related with sizechanged can be another way, I did not tried.

Thanks a lot! Have a nice day :)

**Comment by mattleibow** [comment]
Great to hear!
