### ISSUE TITLE
setting previous signature

### ISSUE THREAD

**Issue by mannyvw** [xamarin/SignaturePad#86]
Thanks for the control. works a treat on my forms app. One request, would be good to be able to set a previously written signature, there only seems to be a GetImage function and no SetImage. 

Be handy to be able to bind to an ImageSource.

thanks

**Comment by mattleibow** [comment]
I don't think that you will be able to go that. `GetImage` creates a bitmap image of the signature. And if there was a `SetImage`, then there is no way to convert the image into a series of points so that it can be drawn as a vector.

If you wish to get and set the signature, you can make use of the `Points` and `Strokes` properties. These are a series of X, Y coordinates in the Xamarin.Forms `Point` type.. If you have to make use of images, then you can possibly achieve what you are looking for with the `GetImageStreamAsync` method and then the `BackgroundImage` property.

However, if you want to just display an image, it may be better to use an `Image` control as this way the user will not be able to accidentally draw over the signature, and there is no need to actually load the control at all.

**Comment by mannyvw** [comment]
Thanks. Yes of course. am displaying an image over the top at the moment, but background image might be better, good idea.

**Comment by mannyvw** [comment]
Actually even better i now store the points and re load them. thanks for your help.
